# Generated by Django 3.2.7 on 2022-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0002_auto_20221102_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='calendar',
            field=models.TextField(default='', verbose_name='Calendar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_stability',
            field=models.TextField(default='', verbose_name='Country Stability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='cultural_tips',
            field=models.TextField(default='', verbose_name='Cultural Tips'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='geography_and_weather',
            field=models.TextField(default='', verbose_name='Geography and Weather'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='getting_around',
            field=models.TextField(default='', verbose_name='Getting Around'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='getting_there',
            field=models.TextField(default='', verbose_name='Getting There'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='language_and_money',
            field=models.TextField(default='', verbose_name='Language and Money'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='medical',
            field=models.TextField(default='', verbose_name='Before you go'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='personal_risk',
            field=models.TextField(default='', verbose_name='Personal Risk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phone_and_power',
            field=models.TextField(default='', verbose_name='Phone and Power'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='summary',
            field=models.TextField(default='', verbose_name='Summary'),
            preserve_default=False,
        ),
    ]
