# Generated by Django 3.2.7 on 2022-11-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0003_auto_20221102_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='standing_travel_advice',
            field=models.TextField(default='', verbose_name='Standing Travel Advice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='travel_risk_summary',
            field=models.TextField(default='', verbose_name='Travel Risk Summary'),
            preserve_default=False,
        ),
    ]
