# Generated by Django 3.2.7 on 2022-11-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0005_remove_country_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='practicalities',
            field=models.TextField(default='', verbose_name='Practicalities'),
            preserve_default=False,
        ),
    ]
