# Generated by Django 3.2.7 on 2022-11-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0006_country_practicalities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='country',
            name='language_and_money',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone_and_power',
        ),
    ]
