# Generated by Django 3.2.7 on 2022-11-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0007_auto_20221107_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='diseases',
            field=models.TextField(default='', verbose_name='Diseases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='medical_advice',
            field=models.TextField(default='', verbose_name='Before you go'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='vaccinations',
            field=models.TextField(default='', verbose_name='Vaccinations'),
            preserve_default=False,
        ),
    ]
